spring:
  application:
   name: Config-Default
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
     defaultZone: http://localhost:8761/eureka
